In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/vanilla_convertibles_data.csv")

df

,S,r,q,bs_vol,credit_spread,redemption,coupon_rate,frequency,maturity_years,conversion_ratio,conversion_price,price_convertible
0,0.495109,0.008807,0.044962,0.288934,0.013333,1000.0,0.060530,1,14.928230,24.857742,40.228916,720.078083
1,22.948247,0.024046,0.031640,0.357933,0.143829,1000.0,0.049526,4,4.913778,31.593804,31.651775,725.022440
2,4.632514,0.039206,0.047870,0.531370,0.138689,1000.0,0.021214,1,10.680081,27.742816,36.045368,131.248142
3,0.632895,0.092328,0.025938,0.679944,0.149453,1000.0,0.063282,2,28.090496,35.163470,28.438604,36.732479
4,295.195831,0.057195,0.023666,0.374704,0.139064,1000.0,0.080437,4,4.429511,19.227176,52.009717,5675.782314
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,122.339119,0.013804,0.046933,0.431888,0.175786,1000.0,0.099901,1,15.545440,2.649497,377.430062,324.137188
999996,2.621224,0.032663,0.018706,0.675430,0.192050,1000.0,0.005265,4,5.245885,14.688062,68.082502,183.398348
999997,0.916692,0.046934,0.002623,0.166985,0.148592,1000.0,0.053740,2,9.956884,37.403045,26.735791,82.620004
999998,2.089208,0.031666,0.018680,0.399931,0.107739,1000.0,0.068094,4,8.251544,23.694405,42.204057,226.549660
999999,635.125374,0.014475,0.041183,0.236669,0.106925,1000.0,0.020139,2,21.285095,28.102078,35.584557,17848.343083

In [3]:
from feature_engineering import engineer_features

df = engineer_features(df, [1,2,3])
df

,S,r,q,bs_vol,credit_spread,redemption,coupon_rate,frequency,maturity_years,conversion_ratio,...,price_normalized,spread_to_vol_ratio,sqrt_maturity,parity,total_remaining_income,real_rate,credit_vol_product,income_to_optionality,rate_spread_ratio,frequency_per_year
0,0.495109,0.008807,0.044962,0.288934,0.013333,1000.0,0.060530,1,14.928230,24.857742,...,6.580747,0.046147,3.863707,12.307302,903.607736,-0.036155,0.003852,65.763195,0.397771,1
1,22.948247,0.024046,0.031640,0.357933,0.143829,1000.0,0.049526,4,4.913778,31.593804,...,6.587581,0.401832,2.216704,725.022440,243.357502,-0.007595,0.051481,0.423041,0.143237,4
2,4.632514,0.039206,0.047870,0.531370,0.138689,1000.0,0.021214,1,10.680081,27.742816,...,4.884680,0.261003,3.268039,128.518990,226.572123,-0.008663,0.073695,1.015203,0.220389,1
3,0.632895,0.092328,0.025938,0.679944,0.149453,1000.0,0.063282,2,28.090496,35.163470,...,3.630521,0.219802,5.300047,22.254794,1777.619508,0.066390,0.101620,22.164459,0.381866,2
4,295.195831,0.057195,0.023666,0.374704,0.139064,1000.0,0.080437,4,4.429511,19.227176,...,8.644140,0.371131,2.104640,5675.782314,356.294656,0.033530,0.052108,0.079601,0.291427,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,122.339119,0.013804,0.046933,0.431888,0.175786,1000.0,0.099901,1,15.545440,2.649497,...,5.784247,0.407019,3.942771,324.137188,1553.006311,-0.033129,0.075920,2.813656,0.072810,1
999996,2.621224,0.032663,0.018706,0.675430,0.192050,1000.0,0.005265,4,5.245885,14.688062,...,5.217098,0.284337,2.290390,38.500702,27.621551,0.013957,0.129716,0.463748,0.145353,4
999997,0.916692,0.046934,0.002623,0.166985,0.148592,1000.0,0.053740,2,9.956884,37.403045,...,4.426283,0.889853,3.155453,34.287089,535.080681,0.044310,0.024813,29.615936,0.240038,2
999998,2.089208,0.031666,0.018680,0.399931,0.107739,1000.0,0.068094,4,8.251544,23.694405,...,5.427369,0.269394,2.872550,49.502539,561.884208,0.012986,0.043088,9.880049,0.227149,4
999999,635.125374,0.014475,0.041183,0.236669,0.106925,1000.0,0.020139,2,21.285095,28.102078,...,9.789722,0.451791,4.613577,17848.343083,428.651766,-0.026707,0.025306,0.021995,0.119236,2

In [4]:
df.to_csv("../data/vanilla_convertibles_data_enhanced.csv", index=False)

In [5]:
df[["price_normalized", "price_convertible"]].describe()

       price_normalized  price_convertible
count     995505.000000      995505.000000
mean           6.941561        6061.756507
std            2.069963       11136.021323
min            2.050991           6.775606
25%            5.359386         211.594270
50%            6.672182         789.117992
75%            8.656486        5746.303957
max           10.907770       54597.933005