In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("vanilla_convertibles_data.csv")

df

,S,r,q,bs_vol,credit_spread,redemption,coupon_rate,frequency,maturity_years,conversion_ratio,conversion_price,price_convertible
0,60.206715,0.071022,0.039404,0.735012,0.058539,100,0.097622,4,7.382009,3.903811,25.615993,251.871345
1,105.023875,0.027703,0.036579,0.636728,0.088371,100,0.033617,4,5.551895,3.345847,29.887795,351.393857
2,457.758451,0.085757,0.050711,0.296074,0.080561,100,0.015080,1,4.899940,6.646872,15.044670,3042.662012
3,356.330783,0.050178,0.010127,0.695026,0.063523,100,0.072563,4,7.476990,6.099752,16.394109,2173.529487
4,450.285185,0.059966,0.028056,0.191209,0.072044,100,0.044351,2,7.298957,5.683709,17.594146,2559.289745
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,417.797364,0.049576,0.021612,0.279284,0.138901,100,0.051653,2,3.380626,4.509955,22.173171,1884.247255
999996,146.413910,0.075163,0.042408,0.683901,0.079158,100,0.046933,2,3.272043,2.481632,40.296064,363.345441
999997,372.745652,0.013845,0.025190,0.277562,0.009923,100,0.012771,4,5.280837,4.031221,24.806379,1502.620190
999998,450.607011,0.076910,0.039229,0.512960,0.057273,100,0.080004,4,6.032408,5.731992,17.445943,2582.875577
999999,396.652325,0.078552,0.037606,0.198678,0.010223,100,0.091929,2,4.799920,8.147592,12.273565,3231.761422

In [8]:
from feature_engineering import engineer_features

df = engineer_features(df, [1,2,3])
df

,S,r,q,bs_vol,credit_spread,redemption,coupon_rate,frequency,maturity_years,conversion_ratio,...,conversion_premium,spread_to_vol_ratio,sqrt_maturity,parity,total_remaining_income,real_rate,credit_vol_product,income_to_optionality,rate_spread_ratio,frequency_per_year
0,60.206715,0.071022,0.039404,0.735012,0.058539,100,0.097622,4,7.382009,3.903811,...,-0.574533,0.079644,2.716985,235.035650,72.064851,0.031617,0.043027,0.153535,0.548172,4
1,105.023875,0.027703,0.036579,0.636728,0.088371,100,0.033617,4,5.551895,3.345847,...,-0.715419,0.138790,2.356246,351.393857,18.663541,-0.008877,0.056268,0.035402,0.238663,4
2,457.758451,0.085757,0.050711,0.296074,0.080561,100,0.015080,1,4.899940,6.646872,...,-0.967134,0.272097,2.213581,3042.662012,7.389180,0.035046,0.023852,0.003706,0.515620,1
3,356.330783,0.050178,0.010127,0.695026,0.063523,100,0.072563,4,7.476990,6.099752,...,-0.953992,0.091397,2.734409,2173.529487,54.255520,0.040051,0.044150,0.013135,0.441313,4
4,450.285185,0.059966,0.028056,0.191209,0.072044,100,0.044351,2,7.298957,5.683709,...,-0.960927,0.376780,2.701658,2559.289745,32.371445,0.031910,0.013775,0.024485,0.454254,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,417.797364,0.049576,0.021612,0.279284,0.138901,100,0.051653,2,3.380626,4.509955,...,-0.946928,0.497346,1.838648,1884.247255,17.461925,0.027964,0.038793,0.018047,0.263034,2
999996,146.413910,0.075163,0.042408,0.683901,0.079158,100,0.046933,2,3.272043,2.481632,...,-0.724780,0.115745,1.808879,363.345441,15.356820,0.032756,0.054136,0.034165,0.487057,2
999997,372.745652,0.013845,0.025190,0.277562,0.009923,100,0.012771,4,5.280837,4.031221,...,-0.933450,0.035750,2.298007,1502.620191,6.744297,-0.011345,0.002754,0.007037,0.582510,4
999998,450.607011,0.076910,0.039229,0.512960,0.057273,100,0.080004,4,6.032408,5.731992,...,-0.961283,0.111651,2.456096,2582.875577,48.261964,0.037680,0.029378,0.014831,0.573173,4
999999,396.652325,0.078552,0.037606,0.198678,0.010223,100,0.091929,2,4.799920,8.147592,...,-0.969057,0.051454,2.190872,3231.761422,44.125143,0.040946,0.002031,0.031367,0.884845,2

In [9]:
df.to_csv("vanilla_convertibles_data.csv", index=False)

KeyboardInterrupt:

In [13]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

X = df.drop(columns=["price_convertible"])
y = df["price_convertible"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=67)

In [15]:
rf = RandomForestRegressor(n_estimators=300, max_depth=None, min_samples_split=2, min_samples_leaf=1, random_state=67)

# GridSearch for best random forest parameters
param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [None, 10, 20 ,30],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2", None]
}

grid_search = GridSearchCV(
    estimator = rf,
    param_grid = param_grid,
    cv = 5,
    scoring="neg_root_mean_squared_error"
)

grid_search.fit(X_train, y_train)

print("Best parameters:", grid_search.best_params_)
print("Best CV RMSE:", -grid_search.best_score_)

KeyboardInterrupt:

In [12]:

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

# Evaluation
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

KeyboardInterrupt:

In [ ]:
# Current mettrics to evaluate model characterisitcs
print("RF RMSE:", rmse)
print("RF MAE:", mae)
print("RF R^2:", r2)

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor(random_state=67)

param_grid_gbr = {
    "n_estimators": [100, 200, 300],
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [2, 3, 4],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "subsample": [0.8, 1.0],
    "max_features": [None, "sqrt", "log2"]
}

grid_search_gbr = GridSearchCV(
    estimator = gbr,
    param_grid = param_grid_gbr,
    cv=5,
    scoring="neg_root_mean_squared_error",
)

grid_search_gbr.fit(X_train, y_train)

print("Best GBR parameters:", grid_search_gbr.best_params_)
print("Best GBR CV RMSE:", -grid_search_gbr.best_score_)

In [ ]:
best_gbr = grid_search_gbr.best_estimator_
best_gbr.fit(X_train, y_train)

y_pred_gbr = best_gbr.predict(X_test)

rmse_gbr = np.sqrt(mean_squared_error(y_test, y_pred_gbr))
mae_gbr = mean_absolute_error(y_test, y_pred_gbr)
r2_gbr = r2_score(y_test, y_pred_gbr)

print("Gradient Boosting Test RMSE:", rmse_gbr)
print("Gradient Boosting Test MAE:", mae_gbr)
print("Gradient Boosting Test R^2:", r2_gbr)